apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: goapp-ingress
  namespace: sandbox
spec:
  ingressClassName: nginx
  rules:
    - host: goapp-65.21.235.195.nip.io
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: goapp-svc
              port: 
                number: 8080
