apiVersion: v1
kind: Service
metadata:
  name: nodeapp-svc
  namespace: sandbox
  labels:
    app: nodeapp
    environment: sandbox
spec:
  ports:
    - port: 3000 
      protocol: TCP
      targetPort: 3000
  selector:
    app: nodeapp
    environment: sandbox
  type: ClusterIP
